wordpress:
  image: wordpress:4.5.2
  links:
    - wordpress_db:mysql
  ports:
    - 8081:80
wordpress_db:
  image: mariadb:10.1.14
  environment:
    MYSQL_ROOT_PASSWORD: examplepass
  volumes:
    - ~/dev/learn/wordpress/wp_html:/var/www/html
phpmyadmin:
  image: corbinu/docker-phpmyadmin
  links:
    - wordpress_db:mysql
  ports:
    - 8181:80
  environment:
    MYSQL_USERNAME: root
    MYSQL_ROOT_PASSWORD: examplepass
